import { LangCode } from './languageStore';

export interface ProductQuestion {
  id: number;
  question: string;
  hint: string;
  dummyAnswer: string;
}

export interface VoiceStrings {
  headerTitle: string;
  stepPrefix: string;
  tapToSpeak: string;
  recording: string;
  tapToStop: string;
  nextQuestion: string;
  previousQuestion: string;
  summaryTitle: string;
  summarySub: string;
  fieldProductName: string;
  fieldDescription: string;
  fieldCategory: string;
  fieldMaterials: string;
  fieldPrice: string;
  fieldQuantity?: string;
  confirmAndPublish: string;
  photoAttached: string;
  photoSub: string;
}

export interface TextStrings {
  headerTitle: string;
  help: string;
  photoAttached: string;
  photoSub: string;
  infoTitle: string;
  infoSub: string;
  labelName: string;
  placeholderName: string;
  labelDescription: string;
  placeholderDescription: string;
  labelCategory: string;
  labelMaterials: string;
  placeholderMaterials: string;
  labelPrice: string;
  placeholderPrice: string;
  labelStock: string;
  placeholderStock: string;
  labelLocation: string;
  placeholderLocation: string;
  saveButton: string;
  successAlert: string;
  errNameAlert: string;
}

export interface ProductDetailsStrings {
  headerTitle: string;
  changePhoto: string;
  imgSuccess: string;
  heading: string;
  subtitle: string;
  speakTitle: string;
  speakSub: string;
  writeTitle: string;
  writeSub: string;
  continueBtn: string;
  enhancedBadge: string;
}

export const PRODUCT_QUESTIONS: Record<LangCode, ProductQuestion[]> = {
  en: [
    {
      id: 1,
      question: 'Tell us the name of your product',
      hint: 'e.g. Handmade Clay Pot, Handloom Cotton Saree, Carved Wooden Box',
      dummyAnswer: 'Decorative Handmade Clay Pot',
    },
    {
      id: 2,
      question: 'Describe your product and its special features',
      hint: 'e.g. Made from 100% natural organic clay, keeps water naturally cool',
      dummyAnswer: 'Made from 100% pure organic black clay with traditional etching that keeps water naturally cool.',
    },
    {
      id: 3,
      question: 'Tell us the category of your product',
      hint: 'e.g. Pottery & Claycraft, Textiles & Handloom, Woodcraft, Metalcraft',
      dummyAnswer: 'Pottery & Claycraft',
    },
    {
      id: 4,
      question: 'What materials were used to make this product?',
      hint: 'e.g. Organic Clay, Natural Terracotta Dyes, Herbal Polish',
      dummyAnswer: 'Organic Black Clay, Terracotta Bio Colors, Herbal Polish',
    },
    {
      id: 5,
      question: 'Tell us the expected price of your product',
      hint: 'e.g. ₹450, ₹1,000 or your expected selling price for this product',
      dummyAnswer: '₹450 (Four hundred fifty rupees)',
    },
    {
      id: 6,
      question: 'How many pieces do you want to sell in bulk or retail?',
      hint: 'e.g. 1 piece for retail, or 20 pieces for bulk wholesale order',
      dummyAnswer: '1 piece (Retail)',
    },
  ],
  hi: [
    {
      id: 1,
      question: 'अपने सामान का नाम बताएं',
      hint: 'जैसे: मिट्टी का घड़ा, हाथ से बुनी साड़ी, लकड़ी की नक्काशीदार घड़ी',
      dummyAnswer: 'सजावटी हस्तनिर्मित मिट्टी का घड़ा',
    },
    {
      id: 2,
      question: 'अपने प्रोडक्ट का विवरण और विशेषताएं बताइए',
      hint: 'जैसे: यह घड़ा 100% प्राकृतिक मिट्टी से बना है, जो पानी को ठंडा रखता है',
      dummyAnswer: 'यह घड़ा 100% शुद्ध काली मिट्टी से बना है। इस पर पारंपरिक नक्काशी की गई है जो पानी को 24 घंटे प्राकृतिक रूप से ठंडा रखती है।',
    },
    {
      id: 3,
      question: 'इसकी कैटेगरी बताएं',
      hint: 'जैसे: हस्तशिल्प - मिट्टी के बर्तन, हथकरघा, काष्ठ शिल्प, धातु शिल्प',
      dummyAnswer: 'हस्तशिल्प - मिट्टी के बर्तन (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'मटेरियल यूज्ड बताइए, क्या सामान लगा है इसको बनाने में?',
      hint: 'जैसे: प्राकृतिक काली मिट्टी, जैविक रंग, कुम्हार का चाक',
      dummyAnswer: 'प्राकृतिक काली मिट्टी, टेराकोटा जैविक रंग, हर्बल पॉलिश',
    },
    {
      id: 5,
      question: 'उत्पाद की अनुमानित कीमत बताएं (Price of Product)',
      hint: 'जैसे: ₹450, ₹1,000 या जितने में आप इस उत्पाद को बेचना चाहते हैं',
      dummyAnswer: '₹450 (चार सौ पचास रुपये)',
    },
    {
      id: 6,
      question: 'बल्क या थोक में कितने पीस बेचने हैं?',
      hint: 'जैसे: 1 पीस (खुदरा / Retail) या 20 पीस (थोक / Wholesale)',
      dummyAnswer: '1 पीस (खुदरा)',
    },
  ],
  bn: [
    {
      id: 1,
      question: 'আপনার পণ্যের নাম বলুন',
      hint: 'যেমন: মাটির পাত্র, তাঁতের শাড়ি, খোদাই করা কাঠের বাক্স',
      dummyAnswer: 'আলংকারিক হাতে তৈরি মাটির পাত্র',
    },
    {
      id: 2,
      question: 'পণ্যের বিবরণ এবং বিশেষ বৈশিষ্ট্যগুলি বলুন',
      hint: 'যেমন: ১০০% প্রাকৃতিক জৈব কাদামাটি দিয়ে তৈরি, যা জলকে প্রাকৃতিকভাবে ঠান্ডা রাখে',
      dummyAnswer: '১০০% খাঁটি প্রাকৃতিক কালো কাদামাটি দিয়ে তৈরি যা জলকে প্রাকৃতিকভাবে শীতল রাখে।',
    },
    {
      id: 3,
      question: 'আপনার পণ্যের শ্রেণী (Category) বলুন',
      hint: 'যেমন: মৃৎশিল্প, টেক্সটাইল ও তাঁত, কাঠের কারুশিল্প, ধাতুশিল্প',
      dummyAnswer: 'মৃৎশিল্প - মাটির পাত্র (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'এটি তৈরিতে কী উপকরণ ব্যবহার করা হয়েছে?',
      hint: 'যেমন: জৈব কাদামাটি, প্রাকৃতিক পোড়ামাটির রং, ভেষজ পালিশ',
      dummyAnswer: 'প্রাকৃতিক কালো মাটি, পোড়ামাটির জৈব রং, ভেষজ পালিশ',
    },
    {
      id: 5,
      question: 'পণ্যের আনুমানিক মূল্য বলুন',
      hint: 'যেমন: ₹৪৫০, ₹১,০০০ বা আপনার বিক্রয় মূল্য',
      dummyAnswer: '₹৪৫০ (চারশত পঞ্চাশ টাকা)',
    },
    {
      id: 6,
      question: 'পাইকারি বা থোকে কতগুলি পিস বিক্রি করতে চান?',
      hint: 'যেমন: ১ টি পিস (খুচরা / Retail) বা ২০ টি পিস (পাইকারি / Wholesale)',
      dummyAnswer: '১ টি পিস (খুচরা)',
    },
  ],
  bho: [
    {
      id: 1,
      question: 'आपन सामान के नाम बनाईं',
      hint: 'जैसे: माटी के घड़ा, हाथ से बनल साड़ी, लकड़ी के नक्काशीदार डिब्बा',
      dummyAnswer: 'सजावटी हाथ से बनावल माटी के घड़ा',
    },
    {
      id: 2,
      question: 'आपन सामान के विवरण आ खासियत बताईं',
      hint: 'जैसे: ई १००% प्राकृतिक माटी से बनल बा, जवन पानी के ठंडा राखेला',
      dummyAnswer: 'ई १००% शुद्ध करिया माटी से बनल बा। एकरा प पारंपरिक नक्काशी बा जवन पानी के ठंडा राखेला।',
    },
    {
      id: 3,
      question: 'एकर वर्ग (Category) बताईं',
      hint: 'जैसे: माटी के बरतन, हथकरघा, काठ के काम, धातु शिल्प',
      dummyAnswer: 'हस्तशिल्प - माटी के बरतन (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'सामग्री (Material) बताईं, का-का लागल बा?',
      hint: 'जैसे: प्राकृतिक करिया माटी, देशी रंग, कुम्हार के चाक',
      dummyAnswer: 'प्राकृतिक करिया माटी, टेराकोटा जैविक रंग, हर्बल पॉलिश',
    },
    {
      id: 5,
      question: 'सामान के अनुमानित दाम बताईं',
      hint: 'जैसे: ₹४५०, ₹१,००० या जेतना में रउआ बेचल चाहत बानी',
      dummyAnswer: '₹४५० (चार सौ पचास रुपया)',
    },
    {
      id: 6,
      question: 'थोक या बल्क में केतना पीस बेचे के बा?',
      hint: 'जैसे: 1 पीस (खुदरा / Retail) भा 20 पीस (थोक माल / Wholesale)',
      dummyAnswer: '1 पीस (खुदरा)',
    },
  ],
  mr: [
    {
      id: 1,
      question: 'तुमच्या उत्पादनाचे नाव सांगा',
      hint: 'उदा. मातीची घागर, हातमाग साडी, लाकडी कोरीव काम',
      dummyAnswer: 'शोभिवंत हस्तनिर्मित मातीचे भांडे',
    },
    {
      id: 2,
      question: 'उत्पादनाचे वर्णन आणि वैशिष्ट्ये सांगा',
      hint: 'उदा. १००% नैसर्गिक मातीपासून बनवले असून पाणी नैसर्गिकरीत्या थंड ठेवते',
      dummyAnswer: '१००% शुद्ध काळ्या मातीपासून बनवले असून पारंपारिक कलाकुसर पाणी नैसर्गिकरीत्या थंड ठेवते.',
    },
    {
      id: 3,
      question: 'उत्पादनाचा वर्ग (Category) सांगा',
      hint: 'उदा. मातीची भांडी, हातमाग कापड, लाकडी वस्तू, धातूकाम',
      dummyAnswer: 'हस्तकला - मातीची भांडी (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'हे बनवण्यासाठी कोणते साहित्य वापरले आहे?',
      hint: 'उदा. नैसर्गिक काळी माती, सेंद्रिय रंग, कुंभाराचे चाक',
      dummyAnswer: 'नैसर्गिक काळी माती, टेराकोटा सेंद्रिय रंग, हर्बल पॉलिश',
    },
    {
      id: 5,
      question: 'उत्पादनाची अंदाजे किंमत सांगा',
      hint: 'उदा. ₹४५०, ₹१,००० किंवा तुम्हाला विक्री करायची असलेली किंमत',
      dummyAnswer: '₹४५० (चारशे पन्नास रुपये)',
    },
    {
      id: 6,
      question: 'घाऊक (Bulk/Wholesale) मध्ये किती नग विकायचे आहेत?',
      hint: 'उदा: १ नग (किरकोळ / Retail) किंवा २० नग (घाऊक / Wholesale)',
      dummyAnswer: '१ नग (किरकोळ)',
    },
  ],
  gu: [
    {
      id: 1,
      question: 'તમારા ઉત્પાદનનું નામ જણાવો',
      hint: 'જેમ કે: માટીનો કલાત્મક ઘડો, હાથવણાટની સાડી, લાકડાની કોતરણી',
      dummyAnswer: 'સુશોભિત હસ્તનિર્મિત માટીનો ઘડો',
    },
    {
      id: 2,
      question: 'ઉત્પાદનનું વર્ણન અને વિશેષતાઓ જણાવો',
      hint: 'જેમ કે: ૧૦૦% કુદરતી માટીમાંથી બનેલ છે, જે પાણીને કુદરતી રીતે ઠંડુ રાખે છે',
      dummyAnswer: '૧૦૦% શુદ્ધ કાળી માટીમાંથી બનાવેલ છે અને પરંપરાગત કોતરણી પાણીને ઠંડુ રાખે છે.',
    },
    {
      id: 3,
      question: 'આની કેટેગરી (Category) જણાવો',
      hint: 'જેમ કે: માટીના વાસણો, ટેક્સટાઇલ અને વણાટકામ, લાકડાકામ, ધાતુકામ',
      dummyAnswer: 'હસ્તકલા - માટીકામ (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'આ બનાવવા કઈ સામગ્રી વાપરવામાં આવી છે?',
      hint: 'જેમ કે: કુદરતી કાળી માટી, ઓર્ગેનિક રંગો, ચાકડો',
      dummyAnswer: 'કુદરતી કાળી માટી, ટેરાકોટા ઓર્ગેનિક રંગો, હર્બલ પોલિશ',
    },
    {
      id: 5,
      question: 'ઉત્પાદનની અંદાજિત કિંમત જણાવો',
      hint: 'જેમ કે: ₹૪૫૦, ₹૧,૦૦૦ અથવા તમે જે ભાવે વેચવા માંગો છો',
      dummyAnswer: '₹૪૫૦ (ચારસો પચાસ રૂપિયા)',
    },
    {
      id: 6,
      question: 'જથ્થાબંધ (Bulk/Wholesale) માં કેટલા પીસ વેચવા છે?',
      hint: 'જેમ કે: ૧ પીસ (છૂટક / Retail) અથવા ૨૦ પીસ (જથ્થાબંધ / Wholesale)',
      dummyAnswer: '૧ પીસ (છૂટક)',
    },
  ],
  raj: [
    {
      id: 1,
      question: 'आपणा माल रो नाम बताओ',
      hint: 'जैसूं: माटी रो घड़ो, हाथ सूं बुणी साड़ी, काठ रो नक्काशीदार सामान',
      dummyAnswer: 'सजावटी हाथ सूं बणायोड़ो माटी रो घड़ो',
    },
    {
      id: 2,
      question: 'आपणा माल रो ब्योरो और खासियत बताओ',
      hint: 'जैसूं: ओ १००% कुदरती माटी सूं बण्यो है, जो पाणी नै ठंडो राखे',
      dummyAnswer: 'ओ घड़ो १००% खरी काळी माटी सूं बण्यो है और परंपरागत नक्काशी पाणी नै ठंडो राखै है।',
    },
    {
      id: 3,
      question: 'माल री श्रेणी (Category) बताओ',
      hint: 'जैसूं: माटी रा बर्तन, हथकरघा, काठ रो काम, धातु शिल्प',
      dummyAnswer: 'हस्तशिल्प - माटी रा बर्तन (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'सामान (Material) बताओ, काई-काई लाग्यो है?',
      hint: 'जैसूं: कुदरती काळी माटी, देशी टेराकोटा रंग, कुम्हार रो चाक',
      dummyAnswer: 'कुदरती काळी माटी, देशी टेराकोटा रंग, हर्बल पॉलिश',
    },
    {
      id: 5,
      question: 'माल री अंदाजन कीमत बताओ',
      hint: 'जैसूं: ₹४५०, ₹१,००० या जित्तै में आप बेचना चाह्वो',
      dummyAnswer: '₹४५० (चार सौ पचास रुप्या)',
    },
    {
      id: 6,
      question: 'थोक (Bulk/Wholesale) में कितना पीस बेचना है?',
      hint: 'जैसूं: 1 पीस (खुदरा / Retail) या 20 पीस (थोक / Wholesale)',
      dummyAnswer: '1 पीस (खुदरा)',
    },
  ],
  kn: [
    {
      id: 1,
      question: 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಹೆಸರನ್ನು ತಿಳಿಸಿ',
      hint: 'ಉದಾ: ಕಲಾತ್ಮಕ ಮಣ್ಣಿನ ಮಡಕೆ, ಕೈಮಗ್ಗ ಹತ್ತಿ ಸೀರೆ, ಕೆತ್ತನೆಯ ಮರದ ವಸ್ತು',
      dummyAnswer: 'ಅಲಂಕಾರಿಕ ಕೈಯಿಂದ ಮಾಡಿದ ಮಣ್ಣಿನ ಮಡಕೆ',
    },
    {
      id: 2,
      question: 'ಉತ್ಪನ್ನದ ವಿವರಣೆ ಮತ್ತು ವಿಶೇಷತೆಗಳನ್ನು ತಿಳಿಸಿ',
      hint: 'ಉದಾ: ೧೦೦% ನೈಸರ್ಗಿಕ ಜೇಡಿಮಣ್ಣಿನಿಂದ ಮಾಡಲಾಗಿದೆ, ನೀರನ್ನು ನೈಸರ್ಗಿಕವಾಗಿ ತಂಪಾಗಿಡುತ್ತದೆ',
      dummyAnswer: '೧೦೦% ಶುದ್ಧ ಸಾವಯವ ಕಪ್ಪು ಮಣ್ಣಿನಿಂದ ಮಾಡಲಾಗಿದ್ದು ನೀರನ್ನು ನೈಸರ್ಗಿಕವಾಗಿ ತಂಪಾಗಿರಿಸುತ್ತದೆ.',
    },
    {
      id: 3,
      question: 'ಉತ್ಪನ್ನದ ವರ್ಗವನ್ನು (Category) ತಿಳಿಸಿ',
      hint: 'ಉದಾ: ಮಣ್ಣಿನ ಪಾತ್ರೆಗಳು, ಜವಳಿ ಮತ್ತು ಕೈಮಗ್ಗ, ಮರದ ಕೆಲಸ, ಲೋಹದ ಕಲೆ',
      dummyAnswer: 'ಹಸ್ತಕಲೆ - ಮಣ್ಣಿನ ಪಾತ್ರೆಗಳು (Pottery & Claycraft)',
    },
    {
      id: 4,
      question: 'ಇದನ್ನು ತಯಾರಿಸಲು ಯಾವ ಸಾಮಗ್ರಿಗಳನ್ನು ಬಳಸಲಾಗಿದೆ?',
      hint: 'ಉದಾ: ನೈಸರ್ಗಿಕ ಜೇಡಿಮಣ್ಣು, ಸಾವಯವ ಬಣ್ಣಗಳು, ಕುಂಬಾರರ ಚಕ್ರ',
      dummyAnswer: 'ನೈಸರ್ಗಿಕ ಕಪ್ಪು ಮಣ್ಣು, ಟೆರಾಕೋಟಾ ಸಾವಯವ ಬಣ್ಣಗಳು, ಗಿಡಮೂಲಿಕೆಗಳ ಪಾಲಿಶ್',
    },
    {
      id: 5,
      question: 'ಉತ್ಪನ್ನದ ಅಂದಾಜು ಬೆಲೆಯನ್ನು ತಿಳಿಸಿ',
      hint: 'ಉದಾ: ₹೪೫೦, ₹೧,೦೦೦ ಅಥವಾ ನೀವು ನಿಗದಿಪಡಿಸುವ ಮಾರಾಟ ಬೆಲೆ',
      dummyAnswer: '₹೪೫೦ (ನಾಲ್ಕು ನೂರ ಐವತ್ತು ರೂಪಾಯಿಗಳು)',
    },
    {
      id: 6,
      question: 'ಒಟ್ಟಾರೆಯಾಗಿ (Bulk/Wholesale) ಎಷ್ಟು ಪೀಸ್‌ಗಳನ್ನು ಮಾರಾಟ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?',
      hint: 'ಉದಾ: ೧ ಪೀಸ್ (ಚಿಲ್ಲರೆ / Retail) ಅಥವಾ ೨೦ ಪೀಸ್‌ಗಳು (ಸಗಟು / Wholesale)',
      dummyAnswer: '೧ ಪೀಸ್ (ಚಿಲ್ಲರೆ)',
    },
  ],
};

export const VOICE_STRINGS: Record<LangCode, VoiceStrings> = {
  en: {
    headerTitle: 'Voice Entry',
    stepPrefix: 'Question',
    tapToSpeak: 'Tap to speak your answer',
    recording: 'Recording... Speak now',
    tapToStop: 'Tap to finish recording',
    nextQuestion: 'Next Question →',
    previousQuestion: '← Back',
    summaryTitle: 'Product Details Summary',
    summarySub: 'Review your product details before submitting',
    fieldProductName: 'Product Name',
    fieldDescription: 'Description & Features',
    fieldCategory: 'Category',
    fieldMaterials: 'Materials Used',
    fieldPrice: 'Expected Price',
    fieldQuantity: 'Order Quantity / Bulk',
    confirmAndPublish: 'Confirm & Publish Product ✓',
    photoAttached: '✨ AI Enhanced Photo Attached',
    photoSub: 'This photo will be shown with your product',
  },
  hi: {
    headerTitle: 'बोलकर विवरण जोड़ें',
    stepPrefix: 'प्रश्न',
    tapToSpeak: 'उत्तर बोलने के लिए माइक छुएं',
    recording: 'रिकॉर्डिंग चालू है... बोलिए',
    tapToStop: 'रिकॉर्डिंग समाप्त करने के लिए टैप करें',
    nextQuestion: 'अगला प्रश्न →',
    previousQuestion: '← पिछला',
    summaryTitle: 'उत्पाद विवरण समीक्षा',
    summarySub: 'उत्पाद पब्लिश करने से पहले अपना विवरण जांचें',
    fieldProductName: 'उत्पाद का नाम',
    fieldDescription: 'विवरण और विशेषताएं',
    fieldCategory: 'श्रेणी (Category)',
    fieldMaterials: 'सामग्री (Materials Used)',
    fieldPrice: 'अनुमानित मूल्य',
    fieldQuantity: 'ऑर्डर मात्रा (Quantity)',
    confirmAndPublish: 'पुष्टि करें और उत्पाद पब्लिश करें ✓',
    photoAttached: '✨ AI एनहांस्ड फोटो संलग्न',
    photoSub: 'यह फोटो आपके उत्पाद के साथ दिखेगी',
  },
  bn: {
    headerTitle: 'ভয়েস এন্ট্রি',
    stepPrefix: 'প্রশ্ন',
    tapToSpeak: 'বলার জন্য মাইক স্পর্শ করুন',
    recording: 'রেকর্ডিং হচ্ছে... বলুন',
    tapToStop: 'রেকর্ডিং শেষ করতে ট্যাপ করুন',
    nextQuestion: 'পরবর্তী প্রশ্ন →',
    previousQuestion: '← পূর্ববর্তী',
    summaryTitle: 'পণ্যের বিবরণ পর্যালোচনা',
    summarySub: 'প্রকাশ করার আগে আপনার পণ্যের বিবরণ পরীক্ষা করুন',
    fieldProductName: 'পণ্যের নাম',
    fieldDescription: 'বিবরণ এবং বৈশিষ্ট্য',
    fieldCategory: 'বিভাগ (Category)',
    fieldMaterials: 'ব্যবহৃত উপাদান',
    fieldPrice: 'প্রত্যাশিত মূল্য',
    fieldQuantity: 'অর্ডারের পরিমাণ',
    confirmAndPublish: 'নিশ্চিত করুন এবং প্রকাশ করুন ✓',
    photoAttached: '✨ AI উন্নত ফটো সংযুক্ত',
    photoSub: 'এই ফটোটি আপনার পণ্যের সাথে দৃশ্যমান হবে',
  },
  bho: {
    headerTitle: 'बोल के विवरण जोड़ीं',
    stepPrefix: 'सवाल',
    tapToSpeak: 'उत्तर बोले खातिर माइक छुईं',
    recording: 'रिकॉर्डिंग चालू बा... बोलीं',
    tapToStop: 'रिकॉर्डिंग बंद करे खातिर टैप करीं',
    nextQuestion: 'अगिला सवाल →',
    previousQuestion: '← पाछे',
    summaryTitle: 'सामान के विवरण समीक्षा',
    summarySub: 'पब्लिश करे से पहिले आपन विवरण जांचीं',
    fieldProductName: 'सामान के नाम',
    fieldDescription: 'विवरण आ खासियत',
    fieldCategory: 'श्रेणी (Category)',
    fieldMaterials: 'लागल सामग्री',
    fieldPrice: 'अनुमानित दाम',
    fieldQuantity: 'ऑर्डर संख्या',
    confirmAndPublish: 'पुष्टि करीं आ पब्लिश करीं ✓',
    photoAttached: '✨ AI एनहांस्ड फोटो लागल बा',
    photoSub: 'ई फोटो रउआ सामान के साथे लउकी',
  },
  mr: {
    headerTitle: 'बोलून माहिती भरा',
    stepPrefix: 'प्रश्न',
    tapToSpeak: 'उत्तर बोलण्यासाठी माइक दाबा',
    recording: 'रेकॉर्डिंग सुरू आहे... बोला',
    tapToStop: 'रेकॉर्डिंग थांबवण्यासाठी टॅप करा',
    nextQuestion: 'पुढील प्रश्न →',
    previousQuestion: '← मागे',
    summaryTitle: 'उत्पादन तपशील पुनरावलोकन',
    summarySub: 'उत्पादन प्रकाशित करण्यापूर्वी तपशील तपासा',
    fieldProductName: 'उत्पादनाचे नाव',
    fieldDescription: 'वर्णन आणि वैशिष्ट्ये',
    fieldCategory: 'वर्ग (Category)',
    fieldMaterials: 'वापरलेले साहित्य',
    fieldPrice: 'अपेक्षित किंमत',
    fieldQuantity: 'ऑर्डर नग संख्या',
    confirmAndPublish: 'खात्री करा आणि प्रकाशित करा ✓',
    photoAttached: '✨ AI संवर्धित फोटो जोडला आहे',
    photoSub: 'हा फोटो तुमच्या उत्पादनासोबत दिसेल',
  },
  gu: {
    headerTitle: 'બોલીને વિગત ઉમેરો',
    stepPrefix: 'પ્રશ્ન',
    tapToSpeak: 'જવાબ બોલવા માઇક દબાવો',
    recording: 'રેકોર્ડિંગ ચાલુ છે... બોલો',
    tapToStop: 'રેકોર્ડિંગ સમાપ્ત કરવા ટેપ કરો',
    nextQuestion: 'આગળનો પ્રશ્ન →',
    previousQuestion: '← પાછળ',
    summaryTitle: 'ઉત્પાદન વિગત સમીક્ષા',
    summarySub: 'પ્રકાશિત કરતા પહેલા વિગત તપાસો',
    fieldProductName: 'ઉત્પાદનનું નામ',
    fieldDescription: 'વર્ણન અને વિશેષતાઓ',
    fieldCategory: 'કેટેગરી (Category)',
    fieldMaterials: 'વપરાયેલ સામગ્રી',
    fieldPrice: 'અંદાજિત કિંમત',
    fieldQuantity: 'ઓર્ડર જથ્થો',
    confirmAndPublish: 'ખાતરી કરો અને પબ્લિશ કરો ✓',
    photoAttached: '✨ AI સુધારેલ ફોટો જોડાયેલ છે',
    photoSub: 'આ ફોટો તમારા ઉત્પાદન સાથે દેખાશે',
  },
  raj: {
    headerTitle: "बोल'र ब्योरो जोड़ो",
    stepPrefix: 'सवाल',
    tapToSpeak: 'बोलबा खातर माइक छुओ',
    recording: 'रिकॉर्डिंग चालू है... बोलो',
    tapToStop: 'रिकॉर्डिंग बंद करबा खातर दबाओ',
    nextQuestion: 'अगलो सवाल →',
    previousQuestion: '← पाछो',
    summaryTitle: 'माल रा ब्योरा री जांच',
    summarySub: 'पब्लिश करबा सूं पैली ब्योरो जांच ल्यो',
    fieldProductName: 'माल रो नाम',
    fieldDescription: 'ब्योरो और खासियत',
    fieldCategory: 'श्रेणी (Category)',
    fieldMaterials: 'लाग्योड़ो सामान',
    fieldPrice: 'अंदाजन भाव',
    fieldQuantity: 'ऑर्डर गिनती',
    confirmAndPublish: 'पक्को करो और पब्लिश करो ✓',
    photoAttached: '✨ AI एनहांस्ड फोटो जुड़्योड़ी है',
    photoSub: 'ओ फोटो आपणा माल रे सागे दीखसी',
  },
  kn: {
    headerTitle: 'ಧ್ವನಿ ಮೂಲಕ ವಿವರಣೆ',
    stepPrefix: 'ಪ್ರಶ್ನೆ',
    tapToSpeak: 'ಉತ್ತರಿಸಲು ಮೈಕ್ ಒತ್ತಿ',
    recording: 'ರೆಕಾರ್ಡಿಂಗ್ ಆಗುತ್ತಿದೆ... ಮಾತನಾಡಿ',
    tapToStop: 'ರೆಕಾರ್ಡಿಂಗ್ ಮುಗಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    nextQuestion: 'ಮುಂದಿನ ಪ್ರಶ್ನೆ →',
    previousQuestion: '← ಹಿಂದಕ್ಕೆ',
    summaryTitle: 'ಉತ್ಪನ್ನ ವಿವರಗಳ ಸಾರಾಂಶ',
    summarySub: 'ಪ್ರಕಟಿಸುವ ಮೊದಲು ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    fieldProductName: 'ಉತ್ಪನ್ನದ ಹೆಸರು',
    fieldDescription: 'ವಿವರಣೆ ಮತ್ತು ವೈಶಿಷ್ಟ್ಯಗಳು',
    fieldCategory: 'ವರ್ಗ (Category)',
    fieldMaterials: 'ಬಳಸಿದ ಸಾಮಗ್ರಿಗಳು',
    fieldPrice: 'ನಿರೀಕ್ಷಿತ ಬೆಲೆ',
    fieldQuantity: 'ಆದೇಶದ ಪ್ರಮಾಣ',
    confirmAndPublish: 'ಖಚಿತಪಡಿಸಿ ಮತ್ತು ಪ್ರಕಟಿಸಿ ✓',
    photoAttached: '✨ AI ಸುಧಾರಿತ ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಿದೆ',
    photoSub: 'ಈ ಫೋಟೋ ನಿಮ್ಮ ಉತ್ಪನ್ನದೊಂದಿಗೆ ಪ್ರದರ್ಶನಗೊಳ್ಳುತ್ತದೆ',
  },
};

export const TEXT_STRINGS: Record<LangCode, TextStrings> = {
  en: {
    headerTitle: 'Add Product by Writing',
    help: 'Help',
    photoAttached: '✨ AI Enhanced Photo Attached',
    photoSub: 'This photo will be displayed with your product',
    infoTitle: 'Write Details Manually',
    infoSub: 'Fill in product name, description and price below',
    labelName: 'Product Name *',
    placeholderName: 'e.g. Decorative Clay Pot',
    labelDescription: 'Product Description *',
    placeholderDescription: 'Describe the craft and key features',
    labelCategory: 'Category *',
    labelMaterials: 'Materials Used *',
    placeholderMaterials: 'e.g. Natural Organic Clay, Herbal Dyes',
    labelPrice: 'Selling Price (₹) *',
    placeholderPrice: 'e.g. 450',
    labelStock: 'Available Stock Quantity *',
    placeholderStock: 'e.g. 25',
    labelLocation: 'Production Village / District',
    placeholderLocation: 'e.g. Rewa, Madhya Pradesh',
    saveButton: 'Save & Publish Product ✓',
    successAlert: 'Product saved successfully and sent for review!',
    errNameAlert: 'Please enter product name.',
  },
  hi: {
    headerTitle: 'लिखकर उत्पाद जोड़ें',
    help: 'सहायता',
    photoAttached: '✨ AI एनहांस्ड फोटो संलग्न',
    photoSub: 'यह फोटो आपके उत्पाद के साथ दिखेगी',
    infoTitle: 'विवरण स्वयं टाइप करें',
    infoSub: 'उत्पाद का नाम, विवरण और मूल्य नीचे भरें',
    labelName: 'उत्पाद का नाम *',
    placeholderName: 'जैसे: सजावटी मिट्टी का घड़ा',
    labelDescription: 'उत्पाद का विवरण *',
    placeholderDescription: 'शिल्प और मुख्य विशेषताओं के बारे में लिखें',
    labelCategory: 'श्रेणी (Category) *',
    labelMaterials: 'इस्तेमाल की गई सामग्री (Materials) *',
    placeholderMaterials: 'जैसे: प्राकृतिक मिट्टी, जैविक रंग',
    labelPrice: 'बिक्री मूल्य (₹) *',
    placeholderPrice: 'जैसे: 450',
    labelStock: 'उपलब्ध स्टॉक मात्रा *',
    placeholderStock: 'जैसे: 25',
    labelLocation: 'गांव / ज़िला',
    placeholderLocation: 'जैसे: रीवा, मध्य प्रदेश',
    saveButton: 'सेव करें और पब्लिश करें ✓',
    successAlert: 'उत्पाद सफलतापूर्वक सेव हो गया है और समीक्षा के लिए भेज दिया गया है!',
    errNameAlert: 'कृपया उत्पाद का नाम भरें।',
  },
  bn: {
    headerTitle: 'লিখে পণ্য যোগ করুন',
    help: 'সাহায্য',
    photoAttached: '✨ AI উন্নত ফটো সংযুক্ত',
    photoSub: 'এই ফটোটি আপনার পণ্যের সাথে প্রদর্শিত হবে',
    infoTitle: 'ম্যানুয়ালি বিবরণ লিখুন',
    infoSub: 'নীচে পণ্যের নাম, বিবরণ এবং মূল্য পূরণ করুন',
    labelName: 'পণ্যের নাম *',
    placeholderName: 'যেমন: আলংকারিক মাটির পাত্র',
    labelDescription: 'পণ্যের বিবরণ *',
    placeholderDescription: 'কারুশিল্প এবং প্রধান বৈশিষ্ট্য বর্ণনা করুন',
    labelCategory: 'বিভাগ (Category) *',
    labelMaterials: 'ব্যবহৃত উপাদান *',
    placeholderMaterials: 'যেমন: প্রাকৃতিক কাদামাটি, ভেষজ রং',
    labelPrice: 'বিক্রয় মূল্য (₹) *',
    placeholderPrice: 'যেমন: 450',
    labelStock: 'মজুদ পরিমাণ *',
    placeholderStock: 'যেমন: 25',
    labelLocation: 'গ্রাম / জেলা',
    placeholderLocation: 'যেমন: বাঁকুড়া, পশ্চিমবঙ্গ',
    saveButton: 'সংরক্ষণ ও প্রকাশ করুন ✓',
    successAlert: 'পণ্য সফলভাবে সংরক্ষিত এবং পর্যালোচনার জন্য জমা হয়েছে!',
    errNameAlert: 'দয়া করে পণ্যের নাম লিখুন।',
  },
  bho: {
    headerTitle: 'लिख के सामान जोड़ीं',
    help: 'मदद',
    photoAttached: '✨ AI एनहांस्ड फोटो लागल बा',
    photoSub: 'ई फोटो रउआ सामान के साथे लउकी',
    infoTitle: 'हाथ से विवरण लिखीं',
    infoSub: 'सामान के नाम, विवरण आ दाम नीचे भरीं',
    labelName: 'सामान के नाम *',
    placeholderName: 'जैसे: सजावटी माटी के घड़ा',
    labelDescription: 'सामान के विवरण *',
    placeholderDescription: 'कला आ खासियत के बारे में लिखीं',
    labelCategory: 'श्रेणी (Category) *',
    labelMaterials: 'लागल सामग्री *',
    placeholderMaterials: 'जैसे: प्राकृतिक करिया माटी, देशी रंग',
    labelPrice: 'बिक्री मूल्य (₹) *',
    placeholderPrice: 'जैसे: 450',
    labelStock: 'उपलब्ध संख्या *',
    placeholderStock: 'जैसे: 25',
    labelLocation: 'गांव / ज़िला',
    placeholderLocation: 'जैसे: आरा, बिहार',
    saveButton: 'सेव करीं आ पब्लिश करीं ✓',
    successAlert: 'सामान सफलतापूर्वक सेव हो गइल बा!',
    errNameAlert: 'कृपया सामान के नाम लिखीं।',
  },
  mr: {
    headerTitle: 'लिहून उत्पादन जोडा',
    help: 'मदत',
    photoAttached: '✨ AI संवर्धित फोटो जोडला आहे',
    photoSub: 'हा फोटो तुमच्या उत्पादनासोबत दिसेल',
    infoTitle: 'माहिती स्वतः टाइप करा',
    infoSub: 'उत्पादनाचे नाव, वर्णन आणि किंमत खाली भरा',
    labelName: 'उत्पादनाचे नाव *',
    placeholderName: 'उदा. शोभिवंत मातीचे भांडे',
    labelDescription: 'उत्पादनाचे वर्णन *',
    placeholderDescription: 'हस्तकला आणि मुख्य वैशिष्ट्यांचे वर्णन करा',
    labelCategory: 'वर्ग (Category) *',
    labelMaterials: 'वापरलेले साहित्य *',
    placeholderMaterials: 'उदा. नैसर्गिक माती, सेंद्रिय रंग',
    labelPrice: 'विक्री किंमत (₹) *',
    placeholderPrice: 'उदा. 450',
    labelStock: 'उपलब्ध साठा *',
    placeholderStock: 'उदा. 25',
    labelLocation: 'गाव / जिल्हा',
    placeholderLocation: 'उदा. कोल्हापूर, महाराष्ट्र',
    saveButton: 'जतन करा आणि प्रकाशित करा ✓',
    successAlert: 'उत्पादन यशस्वीरित्या जतन झाले आहे!',
    errNameAlert: 'कृपया उत्पादनाचे नाव प्रविष्ट करा.',
  },
  gu: {
    headerTitle: 'લખીને ઉત્પાદન ઉમેરો',
    help: 'મદદ',
    photoAttached: '✨ AI સુધારેલ ફોટો જોડાયેલ છે',
    photoSub: 'આ ફોટો તમારા ઉત્પાદન સાથે દેખાશે',
    infoTitle: 'વિગત જાતે લખો',
    infoSub: 'ઉત્પાદનનું નામ, વર્ણન અને કિંમત નીચે ભરો',
    labelName: 'ઉત્પાદનનું નામ *',
    placeholderName: 'જેમ કે: સુશોભિત માટીનો ઘડો',
    labelDescription: 'ઉત્પાદનનું વર્ણન *',
    placeholderDescription: 'કારીગરી અને મુખ્ય વિશેષતાઓ લખો',
    labelCategory: 'કેટેગરી (Category) *',
    labelMaterials: 'વપરાયેલ સામગ્રી *',
    placeholderMaterials: 'જેમ કે: કુદરતી માટી, ઓર્ગેનિક રંગો',
    labelPrice: 'વેચાણ કિંમત (₹) *',
    placeholderPrice: 'જેમ કે: 450',
    labelStock: 'ઉપલબ્ધ જથ્થો *',
    placeholderStock: 'જેમ કે: 25',
    labelLocation: 'ગામ / જિલ્લો',
    placeholderLocation: 'જેમ કે: કચ્છ, ગુજરાત',
    saveButton: 'સાચવો અને પબ્લિશ કરો ✓',
    successAlert: 'ઉત્પાદન સફળતાપૂર્વક સાચવવામાં આવ્યું છે!',
    errNameAlert: 'કૃપા કરીને ઉત્પાદનનું નામ દાખલ કરો.',
  },
  raj: {
    headerTitle: "लिख'र माल जोड़ो",
    help: 'मदद',
    photoAttached: '✨ AI एनहांस्ड फोटो जुड़्योड़ी है',
    photoSub: 'ओ फोटो आपणा माल रे सागे दीखसी',
    infoTitle: 'हाथ सूं ब्योरो लिखो',
    infoSub: 'माल रो नाम, ब्योरो और भाव नीचे भरो',
    labelName: 'माल रो नाम *',
    placeholderName: 'जैसूं: सजावटी माटी रो घड़ो',
    labelDescription: 'माल रो ब्योरो *',
    placeholderDescription: 'कला और खासियतां लिखो',
    labelCategory: 'श्रेणी (Category) *',
    labelMaterials: 'लाग्योड़ो सामान *',
    placeholderMaterials: 'जैसूं: कुदरती काळी माटी, देशी रंग',
    labelPrice: 'बिक्री भाव (₹) *',
    placeholderPrice: 'जैसूं: 450',
    labelStock: 'बच्योड़ो माल *',
    placeholderStock: 'जैसूं: 25',
    labelLocation: 'गांव / जिलो',
    placeholderLocation: 'जैसूं: बाड़मेर, राजस्थान',
    saveButton: 'सेव करो और पब्लिश करो ✓',
    successAlert: 'माल सफलतापूर्वक सेव हो गयो है!',
    errNameAlert: 'कृपया माल रो नाम लिखो।',
  },
  kn: {
    headerTitle: 'ಬರೆದು ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    help: 'ಸಹಾಯ',
    photoAttached: '✨ AI ಸುಧಾರಿತ ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಿದೆ',
    photoSub: 'ಈ ಫೋಟೋ ನಿಮ್ಮ ಉತ್ಪನ್ನದೊಂದಿಗೆ ಪ್ರದರ್ಶನಗೊಳ್ಳುತ್ತದೆ',
    infoTitle: 'ವಿವರಗಳನ್ನು ಸ್ವತಃ ಬರೆಯಿರಿ',
    infoSub: 'ಉತ್ಪನ್ನದ ಹೆಸರು, ವಿವರಣೆ ಮತ್ತು ಬೆಲೆಯನ್ನು ಕೆಳಗೆ ಭರ್ತಿ ಮಾಡಿ',
    labelName: 'ಉತ್ಪನ್ನದ ಹೆಸರು *',
    placeholderName: 'ಉದಾ: ಕಲಾತ್ಮಕ ಮಣ್ಣಿನ ಮಡಕೆ',
    labelDescription: 'ಉತ್ಪನ್ನ ವಿವರಣೆ *',
    placeholderDescription: 'ಕಲೆ ಮತ್ತು ಪ್ರಮುಖ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಬರೆಯಿರಿ',
    labelCategory: 'ವರ್ಗ (Category) *',
    labelMaterials: 'ಬಳಸಿದ ಸಾಮಗ್ರಿಗಳು *',
    placeholderMaterials: 'ಉದಾ: ನೈಸರ್ಗಿಕ ಜೇಡಿಮಣ್ಣು, ಸಾವಯವ ಬಣ್ಣಗಳು',
    labelPrice: 'ಮಾರಾಟ ಬೆಲೆ (₹) *',
    placeholderPrice: 'ಉದಾ: 450',
    labelStock: 'ಲಭ್ಯವಿರುವ ದಾಸ್ತಾನು *',
    placeholderStock: 'ಉದಾ: 25',
    labelLocation: 'ಗ್ರಾಮ / ಜಿಲ್ಲೆ',
    placeholderLocation: 'ಉದಾ: ಮೈಸೂರು, ಕರ್ನಾಟಕ',
    saveButton: 'ಉಳಿಸಿ ಮತ್ತು ಪ್ರಕಟಿಸಿ ✓',
    successAlert: 'ಉತ್ಪನ್ನವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
    errNameAlert: 'ದಯವಿಟ್ಟು ಉತ್ಪನ್ನದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.',
  },
};

export const PRODUCT_DETAILS_STRINGS: Record<LangCode, ProductDetailsStrings> = {
  en: {
    headerTitle: 'Add Product Details',
    changePhoto: 'Change Photo',
    imgSuccess: 'Image uploaded successfully',
    heading: 'Now add product details',
    subtitle: 'You can tell us about your product by voice or type it manually.',
    speakTitle: 'Speak and Add Details',
    speakSub: 'Tap the mic and answer 6 easy questions.',
    writeTitle: 'Write Details',
    writeSub: 'Type the 6 product details manually.',
    continueBtn: 'Continue →',
    enhancedBadge: '✨ OpenCV AI Enhanced',
  },
  hi: {
    headerTitle: 'उत्पाद विवरण जोड़ें',
    changePhoto: 'फोटो बदलें',
    imgSuccess: 'इमेज सफलतापूर्वक अपलोड की गई',
    heading: 'अब उत्पाद विवरण जोड़ें',
    subtitle: 'आप बोलकर या लिखकर अपने उत्पाद की जानकारी दे सकते हैं।',
    speakTitle: 'बोलकर विवरण जोड़ें (Speak)',
    speakSub: 'माइक पर टैप करें और 6 सरल प्रश्नों के उत्तर दें।',
    writeTitle: 'लिखकर विवरण जोड़ें (Write)',
    writeSub: 'उत्पाद के 6 विवरण खुद टाइप करें।',
    continueBtn: 'आगे बढ़ें →',
    enhancedBadge: '✨ OpenCV AI एनहांस्ड फोटो',
  },
  bn: {
    headerTitle: 'পণ্যের বিবরণ যোগ করুন',
    changePhoto: 'ছবি পরিবর্তন করুন',
    imgSuccess: 'ছবি সফলভাবে আপলোড হয়েছে',
    heading: 'এখন পণ্যের বিবরণ যোগ করুন',
    subtitle: 'আপনি মুখে বলে বা লিখে আপনার পণ্যের তথ্য দিতে পারেন।',
    speakTitle: 'মুখে বলে বিবরণ দিন (Speak)',
    speakSub: 'মাইকে চাপুন এবং ৬টি সহজ প্রশ্নের উত্তর দিন।',
    writeTitle: 'লিখে বিবরণ দিন (Write)',
    writeSub: 'পণ্যের ৬টি বিবরণ নিজে টাইপ করুন।',
    continueBtn: 'এগিয়ে যান →',
    enhancedBadge: '✨ OpenCV AI উন্নত ফটো',
  },
  bho: {
    headerTitle: 'सामान के विवरण जोड़ीं',
    changePhoto: 'फोटो बदलीं',
    imgSuccess: 'फोटो सफलता से अपलोड हो गइल',
    heading: 'अब सामान के विवरण जोड़ीं',
    subtitle: 'रउआ बोल के चाहे लिख के आपन सामान के जानकारी दे सकीलें।',
    speakTitle: 'बोल के विवरण जोड़ीं (Speak)',
    speakSub: 'माइक दबाईं आ ६ गो आसान सवाल के जवाब दीं।',
    writeTitle: 'लिख के विवरण जोड़ीं (Write)',
    writeSub: 'सामान के ६ गो विवरण खुद टाइप करीं।',
    continueBtn: 'आगे बढ़ीं →',
    enhancedBadge: '✨ OpenCV AI एनहांस्ड फोटो',
  },
  mr: {
    headerTitle: 'उत्पादन तपशील जोडा',
    changePhoto: 'फोटो बदला',
    imgSuccess: 'फोटो यशस्वीरित्या अपलोड झाला',
    heading: 'आता उत्पादन तपशील जोडा',
    subtitle: 'तुम्ही बोलून किंवा लिहून तुमच्या उत्पादनाची माहिती देऊ शकता.',
    speakTitle: 'बोलून तपशील जोडा (Speak)',
    speakSub: 'माइकवर टॅप करा आणि ६ सोप्या प्रश्नांची उत्तरे द्या.',
    writeTitle: 'लिहून तपशील जोडा (Write)',
    writeSub: 'उत्पादनाचे ६ तपशील स्वतः टाइप करा.',
    continueBtn: 'पुढे जा →',
    enhancedBadge: '✨ OpenCV AI संवर्धित फोटो',
  },
  gu: {
    headerTitle: 'ઉત્પાદનની વિગત ઉમેરો',
    changePhoto: 'ફોટો બદલો',
    imgSuccess: 'ફોટો સફળતાપૂર્વક અપલોડ થયો',
    heading: 'હવે ઉત્પાદનની વિગત ઉમેરો',
    subtitle: 'તમે બોલીને અથવા લખીને તમારા ઉત્પાદનની વિગત આપી શકો છો.',
    speakTitle: 'બોલીને વિગત ઉમેરો (Speak)',
    speakSub: 'માઇક પર ટેપ કરો અને ૬ સરળ પ્રશ્નોના જવાબ આપો.',
    writeTitle: 'લખીને વિગત ઉમેરો (Write)',
    writeSub: 'ઉત્પાદનની ૬ વિગતો જાતે ટાઇપ કરો.',
    continueBtn: 'આગળ વધો →',
    enhancedBadge: '✨ OpenCV AI સુધારેલ ફોટો',
  },
  raj: {
    headerTitle: 'माल रो ब्योरो जोड़ो',
    changePhoto: 'फोटो बदलो',
    imgSuccess: 'फोटो ठीक सूं चढ़ गयो',
    heading: 'अब माल रो ब्योरो जोड़ो',
    subtitle: "आप बोल'र या लिख'र आपणा माल री जानकारी दे सको हो।",
    speakTitle: "बोल'र ब्योरो जोड़ो (Speak)",
    speakSub: 'माइक दबाओ और ६ सोरा सवालां रा जवाब द्यो।',
    writeTitle: "लिख'र ब्योरो जोड़ो (Write)",
    writeSub: 'माल रा ६ ब्योरा खुद लिखो।',
    continueBtn: 'आगे बढ़ो →',
    enhancedBadge: '✨ OpenCV AI एनहांस्ड फोटो',
  },
  kn: {
    headerTitle: 'ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ',
    changePhoto: 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    imgSuccess: 'ಫೋಟೋ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ',
    heading: 'ಈಗ ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ',
    subtitle: 'ನಿಮ್ಮ ಉತ್ಪನ್ನದ ಬಗ್ಗೆ ಮಾತನಾಡುವ ಮೂಲಕ ಅಥವಾ ಬರೆಯುವ ಮೂಲಕ ತಿಳಿಸಬಹುದು.',
    speakTitle: 'ಧ್ವನಿ ಮೂಲಕ ವಿವರಣೆ (Speak)',
    speakSub: 'ಮೈಕ್ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ ೬ ಸುಲಭ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ.',
    writeTitle: 'ಬರೆದು ವಿವರಣೆ ನೀಡಿ (Write)',
    writeSub: 'ಉತ್ಪನ್ನದ ೬ ವಿವರಗಳನ್ನು ನೀವೇ ಟೈಪ್ ಮಾಡಿ.',
    continueBtn: 'ಮುಂದೆ ಸಾಗಿ →',
    enhancedBadge: '✨ OpenCV AI ಸುಧಾರಿತ ಫೋಟೋ',
  },
};
